### ISSUE TITLE
bogus axp173 dependency?

### ISSUE THREAD

**Issue by karlp** [eupn/stm32wb-hal#12]
This is listed as a dependency on crates.io and gets pulled in, but I can't see where it comes from?  Does this need to be republished?

**Comment by eupn** [comment]
Yeah, definitely! Thanks for the catch.

**Comment by eupn** [comment]
@karlp I've published a new version [v0.1.14](https://crates.io/crates/stm32wb-hal/0.1.14) with the `axp173` dependency removed.
